const list = [
  {
    id: 1,
    subTitle: "Morbi non quam nec dui luctus rutrum.",
    body: "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    isActive: false,
    img: "https://images.pexels.com/photos/667838/pexels-photo-667838.jpeg?auto=compress&cs=tinysrgb&h=350",
    title: "A Bright Shining Lie",
  },
  {
    id: 2,
    subTitle: "Donec vitae nisi.",
    body: "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    isActive: false,
    img: "https://images.pexels.com/photos/667838/pexels-photo-667838.jpeg?auto=compress&cs=tinysrgb&h=350",
    title: "Candy",
  },
  {
    id: 3,
    subTitle: "In hac habitasse platea dictumst.",
    body: "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    isActive: false,
    img: "https://images.pexels.com/photos/667838/pexels-photo-667838.jpeg?auto=compress&cs=tinysrgb&h=350",
    title: "Fountain, The",
  },
  {
    id: 4,
    subTitle: "Sed ante.",
    body: "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    isActive: false,
    img: "https://images.pexels.com/photos/667838/pexels-photo-667838.jpeg?auto=compress&cs=tinysrgb&h=350",
    title: "Baby On Board",
  },
  {
    id: 5,
    subTitle: "Maecenas tincidunt lacus at velit.",
    body: "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    isActive: false,
    img: "https://images.pexels.com/photos/667838/pexels-photo-667838.jpeg?auto=compress&cs=tinysrgb&h=350",
    title: "Harvest",
  },
  {
    id: 6,
    subTitle: "Suspendisse ornare consequat lectus.",
    body: "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    isActive: true,
    img: "https://images.pexels.com/photos/667838/pexels-photo-667838.jpeg?auto=compress&cs=tinysrgb&h=350",
    title: "From Beginning to End (Do Começo ao Fim)",
  },
  {
    id: 7,
    subTitle: "Etiam faucibus cursus urna.",
    body: "In congue. Etiam justo. Etiam pretium iaculis justo.",
    isActive: true,
    img: "https://images.pexels.com/photos/667838/pexels-photo-667838.jpeg?auto=compress&cs=tinysrgb&h=350",
    title: "Invisible War, The",
  },
  {
    id: 8,
    subTitle:
      "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.",
    body: "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    isActive: false,
    img: "https://images.pexels.com/photos/667838/pexels-photo-667838.jpeg?auto=compress&cs=tinysrgb&h=350",
    title: "FC Venus",
  },
  {
    id: 9,
    subTitle: "Nunc rhoncus dui vel sem.",
    body: "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    isActive: true,
    img: "https://images.pexels.com/photos/667838/pexels-photo-667838.jpeg?auto=compress&cs=tinysrgb&h=350",
    title: "On His Own (a.k.a. My Apprenticeship) (V lyudyakh)",
  },
  {
    id: 10,
    subTitle: "Vivamus vestibulum sagittis sapien.",
    body: "Fusce consequat. Nulla nisl. Nunc nisl.",
    isActive: true,
    img: "https://images.pexels.com/photos/667838/pexels-photo-667838.jpeg?auto=compress&cs=tinysrgb&h=350",
    title: "Man Who Saves the World, The (Dünyayi Kurtaran Adam)",
  },
];

export default list;
